---
- name: application deployment
  hosts: all
  become: yes
  tasks:
     - name: install jdb
       apt:
        - name: openjk-8-jdk
        - state: present
        - update_cache: yes
      - name: install tomcat
        apt:
          - name: tomcat8
      - name: copy the file
        get_url:
          - url: https://referenceappkhaja.s3-us-west-2.amazonaws.com/gameoflife.war
          - dest: /var/lib/tomcat8/webapps
          